//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp4
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BAU_EP2MY_SITEntities : DbContext
    {
        public BAU_EP2MY_SITEntities()
            : base("name=BAU_EP2MY_SITEntities")
        {
            var objectContext = (this as IObjectContextAdapter).ObjectContext;
            objectContext.CommandTimeout = 1200;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {

      
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<flights> flights { get; set; }
        public virtual DbSet<routes> routes { get; set; }
        public virtual DbSet<subscriptions> subscriptions { get; set; }
    }
}
