//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp4
{
    using System;
    using System.Collections.Generic;
    
    public partial class subscriptions
    {
        public int ID { get; set; }
        public Nullable<double> agency_id { get; set; }
        public Nullable<double> origin_city_id { get; set; }
        public Nullable<double> destination_city_id { get; set; }
    }
}
